apiVersion: v1
kind: Service
metadata:
  name: go-service
spec:
  type: NodePort
  selector:
    app: go-service
  ports:
    - port: 80        # service port
      targetPort: 3000 # container port
      nodePort: 30550 # accessible from localhost